auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # kubernetes to dockerhub
#   k8s.gcr.io/kube-apiserver: chengleqi/kube-apiserver
#   k8s.gcr.io/kube-controller-manager: chengleqi/kube-controller-manager
#   k8s.gcr.io/kube-scheduler: chengleqi/kube-scheduler
#   k8s.gcr.io/kube-proxy: chengleqi/kube-proxy
#   k8s.gcr.io/pause: chengleqi/pause
#   k8s.gcr.io/etcd: chengleqi/etcd
#   coredns/coredns: chengleqi/coredns
  # knative to dockerhub
#   gcr.io/knative-releases/knative.dev/serving/cmd/queue: chengleqi/knative-queue
#   gcr.io/knative-releases/knative.dev/serving/cmd/activator: chengleqi/knative-activator
#   gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler: chengleqi/knative-autoscaler
#   gcr.io/knative-releases/knative.dev/serving/cmd/controller: chengleqi/knative-controller
#   gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping: chengleqi/knative-domain-mapping
#   gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook: chengleqi/knative-domain-mapping-webhook
#   gcr.io/knative-releases/knative.dev/serving/cmd/webhook: chengleqi/knative-webhook
  # tekton to dockerhub
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller: chengleqi/tekton-controller
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook: chengleqi/tekton-webhook
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter: chengleqi/tekton-kubeconfigwriter
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init: chengleqi/tekton-git-init
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint: chengleqi/tekton-entrypoint
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop: chengelqi/tekton-nop
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter: chengleqi/tekton-imagedigestexporter
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init: chengleqi/tekton-pullrequest-init
  gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit: chengleqi/tekton-workingdirinit
  gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard: chengleqi/tekton-dashboard
