auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # kubernetes to dockerhub
  k8s.gcr.io/kube-apiserver: chengleqi/kube-apiserver
  k8s.gcr.io/kube-controller-manager: chengleqi/kube-controller-manager
  k8s.gcr.io/kube-scheduler: chengleqi/kube-scheduler
  k8s.gcr.io/kube-proxy: chengleqi/kube-proxy
  k8s.gcr.io/pause: chengleqi/pause
  k8s.gcr.io/etcd: chengleqi/etcd
  coredns/coredns: chengleqi/coredns
